version: "3.8"

services:
  my-db:
    image: postgres
    container_name: horizon-bd
    restart: always
    environment:
      POSTGRES_DB: cleanfastapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
